FROM nem75/baghira-wp_php:base

COPY xdebug_options.conf /
ENV PECL_DEPS "autoconf gcc libc-dev make"

RUN apk -U --no-cache add \
    rsync openssh-client \
    ${PECL_DEPS} \
  && pecl install xdebug \
  && docker-php-ext-enable xdebug \
  && apk del --purge ${PECL_DEPS} \
  && cat /xdebug_options.conf >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

